vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    mappings:
        cartes:
            uri_prefix: /images/cartes
            upload_destination: '%kernel.project_dir%/public/images/cartes'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
